#!bin/python3
#Script to extract coordinates for Spike protein
#python3
#copyright 2022
#Written by Mike Mwanga
#April 2022

import pandas as pd

#Load the hits.txt file generated by blast
hits_data = pd.read_table("hits.txt", sep = "\t", usecols=[0,1,2], names = ["ID", "start","stop"])

#create length column for length of blast results
hits_data["length"] =  hits_data.apply(lambda x: x.stop - x.start, axis=1)

#filter hits > 3800 since length of gene is 3000
hits  = hits_data[hits_data["length"] > 3000]

#drop lenght column
hits = hits.drop("length", axis=1)

#write to another file
hits.to_csv("sequence_coordinates.txt", sep = "\t", header=False, index=False)
